name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v6
        
      - name: Create Docker image with Blender
        run: docker build --build-arg GAME_CI_UNITY_EDITOR_IMAGE=unityci/editor:ubuntu-6000.2.10f1-webgl-3.2.0 . -t axwabo/unity-blender

      - uses: game-ci/unity-builder@v4.7.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: 
            - StandaloneWindows64
            - StandaloneLinux64
          customImage: axwabo/unity-blender
          runAsHostUser: true
          
      - working-directory: build/StandaloneWindows64/StandaloneWindows64
        run: zip . ${{ github.workspace }}/SpaceTransit-win-x64.zip
          
      - working-directory: build/StandaloneLinux64/StandaloneLinux64
        run: zip . ${{ github.workspace }}/SpaceTransit-linux-x64.zip
        
      - uses: softprops/action-gh-release@v2
        with:
          files: SpaceTransit-*-x64.zip

 
